list: $/nielsvandendries/janus/models/facturen/columns.yaml
modelClass: NielsVanDenDries\Janus\Models\Facturen
title: Facturen
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nielsvandendries/janus/facturen/update/:id'
