list: $/nielsvandendries/janus/models/projecten/columns.yaml
modelClass: NielsVanDenDries\Janus\Models\Projecten
title: Projecten
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nielsvandendries/janus/projecten/update/:id'
