list: $/nielsvandendries/janus/models/bedrijfsgegevens/columns.yaml
modelClass: NielsVanDenDries\Janus\Models\Bedrijfsgegevens
title: Bedrijfsgegevens
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nielsvandendries/janus/bedrijfsgegevens/update/:id'
