title: Inkomsten
modelClass: NielsVanDenDries\Janus\Models\Inkomsten
list: $/nielsvandendries/janus/models/inkomsten/columns.yaml
recordUrl: 'nielsvandendries/janus/inkomsten/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
