list: $/nielsvandendries/janus/models/klanten/columns.yaml
modelClass: NielsVanDenDries\Janus\Models\Klanten
title: Klanten
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nielsvandendries/janus/klanten/update/:id'
