name: Offertes
form: $/nielsvandendries/janus/models/offertes/fields.yaml
modelClass: NielsVanDenDries\Janus\Models\Offertes
defaultRedirect: nielsvandendries/janus/offertes
create:
    redirect: 'nielsvandendries/janus/offertes/update/:id'
    redirectClose: nielsvandendries/janus/offertes
update:
    redirect: nielsvandendries/janus/offertes
    redirectClose: nielsvandendries/janus/offertes
