list: $/nielsvandendries/janus/models/offertes/columns.yaml
modelClass: NielsVanDenDries\Janus\Models\Offertes
title: Offertes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nielsvandendries/janus/offertes/update/:id'
