list: $/nielsvandendries/janus/models/producten/columns.yaml
modelClass: NielsVanDenDries\Janus\Models\Producten
title: Producten
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nielsvandendries/janus/producten/update/:id'
